[book]
authors = ["Casey Lee"]
language = "en"
multilingual = false
src = "src"
title = "act - User Guide | Manual | Docs | Documentation"

[output.html]
git-repository-url = "https://github.com/nektos/act-docs"
